-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.roles (
  id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
  nombre text NOT NULL UNIQUE,
  descripcion text,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.usuarios (
  id uuid NOT NULL,
  nombre text NOT NULL,
  apellido text,
  telefono text,
  rol_id integer NOT NULL,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  email text,
  oficina_id bigint,
  id_muestra integer NOT NULL DEFAULT nextval('usuarios_id_muestra_seq'::regclass) UNIQUE,
  contrasena text,
  CONSTRAINT usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.roles(id),
  CONSTRAINT usuarios_oficina_id_fkey FOREIGN KEY (oficina_id) REFERENCES public.oficinas(id)
);
CREATE TABLE public.vendedores (
  id integer NOT NULL DEFAULT nextval('vendedores_id_seq'::regclass),
  nombre text NOT NULL,
  apellido text,
  telefono text,
  email text,
  oficina text,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  creado_por uuid,
  codigo text,
  CONSTRAINT vendedores_pkey PRIMARY KEY (id),
  CONSTRAINT vendedores_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.clientes (
  id integer NOT NULL DEFAULT nextval('clientes_id_seq'::regclass),
  nombre text NOT NULL,
  apellido text,
  email text,
  telefono text,
  rfc text,
  direccion text,
  ciudad text,
  estado text,
  cp text,
  fecha_nac date,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  creado_por uuid,
  curp text,
  colonia text,
  calle text,
  numero_ext text,
  numero_int text,
  CONSTRAINT clientes_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.polizas (
  id integer NOT NULL DEFAULT nextval('polizas_id_seq'::regclass),
  numero_poliza text NOT NULL UNIQUE,
  cliente_id integer NOT NULL,
  vendedor_id integer,
  anio integer,
  color text,
  placas text,
  num_serie text,
  aseguradora text,
  tipo_poliza text,
  forma_pago text,
  fecha_inicio date,
  fecha_fin date,
  estatus text DEFAULT 'COTIZACION'::text,
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  creado_por uuid,
  actualizado_por uuid,
  actualizado_at timestamp with time zone,
  constancia text UNIQUE,
  num_motor text,
  capacidad text DEFAULT '4 OCUPANTES'::text,
  uso text DEFAULT 'SERVICIO PUBLICO'::text,
  tipo_servicio text DEFAULT 'TAXI'::text,
  descuento numeric DEFAULT 0,
  recargo numeric DEFAULT 0,
  en_letras text,
  hora_inicio text DEFAULT '00:00:00 hrs.'::text,
  hora_fin text DEFAULT '23:59:59 hrs.'::text,
  emision_hora text,
  conductor_habitual text,
  conductor_sexo text,
  conductor_edad text,
  cp_asegurado text,
  uso_tarifario text DEFAULT '15'::text,
  concesionario_id integer,
  oficina_id bigint,
  vehiculo_amis_id integer,
  cobertura_id uuid NOT NULL,
  CONSTRAINT polizas_pkey PRIMARY KEY (id),
  CONSTRAINT polizas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT polizas_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.vendedores(id),
  CONSTRAINT polizas_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT polizas_actualizado_por_fkey FOREIGN KEY (actualizado_por) REFERENCES public.usuarios(id),
  CONSTRAINT polizas_concesionario_id_fkey FOREIGN KEY (concesionario_id) REFERENCES public.concesionarios(id),
  CONSTRAINT polizas_oficina_id_fkey FOREIGN KEY (oficina_id) REFERENCES public.oficinas(id),
  CONSTRAINT polizas_vehiculo_amis_id_fkey FOREIGN KEY (vehiculo_amis_id) REFERENCES public.vehiculos_amis(id),
  CONSTRAINT polizas_cobertura_id_fkey FOREIGN KEY (cobertura_id) REFERENCES public.coberturas(id)
);
CREATE TABLE public.polizas_historial (
  id integer NOT NULL DEFAULT nextval('polizas_historial_id_seq'::regclass),
  poliza_id integer NOT NULL,
  estatus_ant text,
  estatus_nuevo text,
  notas text,
  cambiado_por uuid,
  cambiado_at timestamp with time zone DEFAULT now(),
  CONSTRAINT polizas_historial_pkey PRIMARY KEY (id),
  CONSTRAINT polizas_historial_poliza_id_fkey FOREIGN KEY (poliza_id) REFERENCES public.polizas(id),
  CONSTRAINT polizas_historial_cambiado_por_fkey FOREIGN KEY (cambiado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.pagos (
  id integer NOT NULL DEFAULT nextval('pagos_id_seq'::regclass),
  poliza_id integer NOT NULL,
  monto numeric NOT NULL,
  fecha_pago date,
  fecha_vencimiento date,
  forma_pago text,
  referencia text,
  estatus text DEFAULT 'PENDIENTE'::text,
  notas text,
  creado_por uuid,
  autorizado_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  recibido_por uuid,
  aplicado_por uuid,
  CONSTRAINT pagos_pkey PRIMARY KEY (id),
  CONSTRAINT pagos_poliza_id_fkey FOREIGN KEY (poliza_id) REFERENCES public.polizas(id),
  CONSTRAINT pagos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT pagos_autorizado_por_fkey FOREIGN KEY (autorizado_por) REFERENCES public.usuarios(id),
  CONSTRAINT pagos_recibido_por_fkey FOREIGN KEY (recibido_por) REFERENCES public.usuarios(id),
  CONSTRAINT pagos_aplicado_por_fkey FOREIGN KEY (aplicado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.siniestros (
  id integer NOT NULL DEFAULT nextval('siniestros_id_seq'::regclass),
  numero_siniestro text NOT NULL UNIQUE,
  poliza_id integer NOT NULL,
  cliente_id integer NOT NULL,
  fecha_siniestro date NOT NULL,
  hora_siniestro time without time zone,
  ubicacion text,
  tipo_siniestro text,
  descripcion text,
  tercero_nombre text,
  tercero_telefono text,
  tercero_vehiculo text,
  tercero_placas text,
  ajustador_id uuid,
  supervisor_id uuid,
  estatus text DEFAULT 'REPORTADO'::text,
  resolucion text,
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  reportado_por uuid,
  CONSTRAINT siniestros_pkey PRIMARY KEY (id),
  CONSTRAINT siniestros_poliza_id_fkey FOREIGN KEY (poliza_id) REFERENCES public.polizas(id),
  CONSTRAINT siniestros_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT siniestros_ajustador_id_fkey FOREIGN KEY (ajustador_id) REFERENCES public.usuarios(id),
  CONSTRAINT siniestros_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.usuarios(id),
  CONSTRAINT siniestros_reportado_por_fkey FOREIGN KEY (reportado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.siniestros_historial (
  id integer NOT NULL DEFAULT nextval('siniestros_historial_id_seq'::regclass),
  siniestro_id integer NOT NULL,
  estatus_ant text,
  estatus_nuevo text,
  notas text,
  cambiado_por uuid,
  cambiado_at timestamp with time zone DEFAULT now(),
  CONSTRAINT siniestros_historial_pkey PRIMARY KEY (id),
  CONSTRAINT siniestros_historial_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id),
  CONSTRAINT siniestros_historial_cambiado_por_fkey FOREIGN KEY (cambiado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.siniestros_documentos (
  id integer NOT NULL DEFAULT nextval('siniestros_documentos_id_seq'::regclass),
  siniestro_id integer NOT NULL,
  tipo text NOT NULL,
  url text NOT NULL,
  nombre_archivo text,
  subido_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT siniestros_documentos_pkey PRIMARY KEY (id),
  CONSTRAINT siniestros_documentos_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id),
  CONSTRAINT siniestros_documentos_subido_por_fkey FOREIGN KEY (subido_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.metas_ventas (
  id integer NOT NULL DEFAULT nextval('metas_ventas_id_seq'::regclass),
  vendedor_id integer,
  oficina text,
  mes integer NOT NULL,
  anio integer NOT NULL,
  meta_polizas integer,
  meta_prima numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT metas_ventas_pkey PRIMARY KEY (id),
  CONSTRAINT metas_ventas_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.vendedores(id)
);
CREATE TABLE public.concesionarios (
  id integer NOT NULL DEFAULT nextval('concesionarios_id_seq'::regclass),
  cliente_id integer NOT NULL,
  nombre text NOT NULL,
  apellido1 text,
  apellido2 text,
  created_at timestamp with time zone DEFAULT now(),
  creado_por uuid,
  telefono text,
  CONSTRAINT concesionarios_pkey PRIMARY KEY (id),
  CONSTRAINT concesionarios_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT concesionarios_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.oficinas (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  nombre text,
  CONSTRAINT oficinas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vehiculos_amis (
  id integer NOT NULL DEFAULT nextval('vehiculos_amis_id_seq'::regclass),
  cve integer NOT NULL,
  mr text,
  marca text NOT NULL,
  tipo text NOT NULL,
  dc text,
  dl text,
  anio integer NOT NULL,
  CONSTRAINT vehiculos_amis_pkey PRIMARY KEY (id)
);
CREATE TABLE public.coberturas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  prima_neta numeric NOT NULL,
  prima_total numeric NOT NULL,
  oficina_id bigint,
  duracion_meses smallint NOT NULL DEFAULT 12,
  activa boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  grupo_id bigint NOT NULL,
  vigente_desde date NOT NULL DEFAULT CURRENT_DATE,
  activa_hasta date,
  CONSTRAINT coberturas_pkey PRIMARY KEY (id),
  CONSTRAINT coberturas_oficina_id_fkey FOREIGN KEY (oficina_id) REFERENCES public.oficinas(id),
  CONSTRAINT coberturas_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos_coberturas(id)
);
CREATE TABLE public.cobertura_rubros (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cobertura_id uuid NOT NULL,
  rubro text NOT NULL,
  prima_neta numeric NOT NULL DEFAULT 0,
  monto_maximo text,
  es_sublimite boolean NOT NULL DEFAULT false,
  orden smallint NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cobertura_rubros_pkey PRIMARY KEY (id),
  CONSTRAINT cobertura_rubros_cobertura_id_fkey FOREIGN KEY (cobertura_id) REFERENCES public.coberturas(id)
);
CREATE TABLE public.grupos_coberturas (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  nombre text NOT NULL UNIQUE,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT grupos_coberturas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.configuracion_costos (
  clave text NOT NULL,
  valor text NOT NULL,
  tipo text NOT NULL DEFAULT 'number'::text,
  descripcion text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  vigente_desde date NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT configuracion_costos_pkey PRIMARY KEY (clave, vigente_desde),
  CONSTRAINT configuracion_costos_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.usuarios(id)
);
CREATE TABLE public.configuracion_sistema (
  clave text NOT NULL,
  valor text NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT configuracion_sistema_pkey PRIMARY KEY (clave),
  CONSTRAINT configuracion_sistema_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.usuarios(id)
);
CREATE TABLE public.polizas_cofisem (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  fecha_corte date NOT NULL DEFAULT CURRENT_DATE,
  folio text,
  aseguradora text,
  numero_poliza text,
  fecha_emision date DEFAULT CURRENT_DATE,
  vigencia_inicio date,
  vigencia_fin date,
  vendedor_nombre text,
  asegurado_nombre text,
  vale numeric DEFAULT 0,
  prima_anual numeric DEFAULT 0,
  prima_neta numeric DEFAULT 0,
  prima_primer_pago numeric DEFAULT 0,
  cobertura text,
  placas text,
  tipo text DEFAULT 'COCHE'::text,
  forma_pago text DEFAULT 'CONTADO'::text,
  efectivo numeric DEFAULT 0,
  cheque numeric DEFAULT 0,
  tdc numeric DEFAULT 0,
  autorizacion text,
  pol_pend_pago numeric DEFAULT 0,
  fotos boolean DEFAULT false,
  factura boolean DEFAULT false,
  t_circ boolean DEFAULT false,
  identif boolean DEFAULT false,
  pol_ant boolean DEFAULT false,
  otro boolean DEFAULT false,
  observaciones text,
  oficina_id bigint,
  creado_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  poliza_id integer,
  telefono text,
  CONSTRAINT polizas_cofisem_pkey PRIMARY KEY (id),
  CONSTRAINT corte_registros_oficina_id_fkey FOREIGN KEY (oficina_id) REFERENCES public.oficinas(id),
  CONSTRAINT corte_registros_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT corte_registros_poliza_id_fkey FOREIGN KEY (poliza_id) REFERENCES public.polizas(id)
);
CREATE TABLE public.aseguradoras (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  nombre text,
  CONSTRAINT aseguradoras_pkey PRIMARY KEY (id)
);