-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.clientes (
  id integer NOT NULL DEFAULT nextval('clientes_id_seq'::regclass),
  nombre text NOT NULL,
  apellido text,
  email text,
  telefono text,
  rfc text,
  direccion text,
  ciudad text,
  estado text,
  cp text,
  fecha_nac date,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  creado_por uuid,
  curp text,
  colonia text,
  CONSTRAINT clientes_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.metas_ventas (
  id integer NOT NULL DEFAULT nextval('metas_ventas_id_seq'::regclass),
  vendedor_id integer,
  oficina text,
  mes integer NOT NULL,
  anio integer NOT NULL,
  meta_polizas integer,
  meta_prima numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT metas_ventas_pkey PRIMARY KEY (id),
  CONSTRAINT metas_ventas_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.vendedores(id)
);
CREATE TABLE public.pagos (
  id integer NOT NULL DEFAULT nextval('pagos_id_seq'::regclass),
  poliza_id integer NOT NULL,
  monto numeric NOT NULL,
  fecha_pago date,
  fecha_vencimiento date,
  forma_pago text,
  referencia text,
  estatus text DEFAULT 'PENDIENTE'::text,
  notas text,
  creado_por uuid,
  autorizado_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pagos_pkey PRIMARY KEY (id),
  CONSTRAINT pagos_poliza_id_fkey FOREIGN KEY (poliza_id) REFERENCES public.polizas(id),
  CONSTRAINT pagos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT pagos_autorizado_por_fkey FOREIGN KEY (autorizado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.polizas (
  id integer NOT NULL DEFAULT nextval('polizas_id_seq'::regclass),
  numero_poliza text NOT NULL UNIQUE,
  cliente_id integer NOT NULL,
  vendedor_id integer,
  marca text,
  modelo text,
  anio integer,
  color text,
  placas text,
  num_serie text,
  aseguradora text,
  tipo_poliza text,
  cobertura text,
  prima_neta numeric,
  prima_total numeric,
  forma_pago text,
  fecha_inicio date,
  fecha_fin date,
  estatus text DEFAULT 'COTIZACION'::text,
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  creado_por uuid,
  actualizado_por uuid,
  actualizado_at timestamp with time zone,
  constancia text UNIQUE,
  num_motor text,
  cod_amis text,
  capacidad text DEFAULT '4 OCUPANTES'::text,
  version text,
  uso text DEFAULT 'SERVICIO PUBLICO'::text,
  tipo_servicio text DEFAULT 'TAXI'::text,
  descuento numeric DEFAULT 0,
  recargo numeric DEFAULT 0,
  derechos numeric DEFAULT 400,
  iva numeric,
  en_letras text,
  hora_inicio text DEFAULT '00:00:00 hrs.'::text,
  hora_fin text DEFAULT '23:59:59 hrs.'::text,
  emision_hora text,
  conductor_habitual text,
  conductor_sexo text,
  conductor_edad text,
  cp_asegurado text,
  uso_tarifario text DEFAULT '15'::text,
  CONSTRAINT polizas_pkey PRIMARY KEY (id),
  CONSTRAINT polizas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT polizas_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.vendedores(id),
  CONSTRAINT polizas_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT polizas_actualizado_por_fkey FOREIGN KEY (actualizado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.polizas_historial (
  id integer NOT NULL DEFAULT nextval('polizas_historial_id_seq'::regclass),
  poliza_id integer NOT NULL,
  estatus_ant text,
  estatus_nuevo text,
  notas text,
  cambiado_por uuid,
  cambiado_at timestamp with time zone DEFAULT now(),
  CONSTRAINT polizas_historial_pkey PRIMARY KEY (id),
  CONSTRAINT polizas_historial_poliza_id_fkey FOREIGN KEY (poliza_id) REFERENCES public.polizas(id),
  CONSTRAINT polizas_historial_cambiado_por_fkey FOREIGN KEY (cambiado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.roles (
  id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
  nombre text NOT NULL UNIQUE,
  descripcion text,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.siniestros (
  id integer NOT NULL DEFAULT nextval('siniestros_id_seq'::regclass),
  numero_siniestro text NOT NULL UNIQUE,
  poliza_id integer NOT NULL,
  cliente_id integer NOT NULL,
  fecha_siniestro date NOT NULL,
  hora_siniestro time without time zone,
  ubicacion text,
  tipo_siniestro text,
  descripcion text,
  tercero_nombre text,
  tercero_telefono text,
  tercero_vehiculo text,
  tercero_placas text,
  ajustador_id uuid,
  supervisor_id uuid,
  estatus text DEFAULT 'REPORTADO'::text,
  resolucion text,
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  reportado_por uuid,
  CONSTRAINT siniestros_pkey PRIMARY KEY (id),
  CONSTRAINT siniestros_poliza_id_fkey FOREIGN KEY (poliza_id) REFERENCES public.polizas(id),
  CONSTRAINT siniestros_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT siniestros_ajustador_id_fkey FOREIGN KEY (ajustador_id) REFERENCES public.usuarios(id),
  CONSTRAINT siniestros_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.usuarios(id),
  CONSTRAINT siniestros_reportado_por_fkey FOREIGN KEY (reportado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.siniestros_documentos (
  id integer NOT NULL DEFAULT nextval('siniestros_documentos_id_seq'::regclass),
  siniestro_id integer NOT NULL,
  tipo text NOT NULL,
  url text NOT NULL,
  nombre_archivo text,
  subido_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT siniestros_documentos_pkey PRIMARY KEY (id),
  CONSTRAINT siniestros_documentos_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id),
  CONSTRAINT siniestros_documentos_subido_por_fkey FOREIGN KEY (subido_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.siniestros_historial (
  id integer NOT NULL DEFAULT nextval('siniestros_historial_id_seq'::regclass),
  siniestro_id integer NOT NULL,
  estatus_ant text,
  estatus_nuevo text,
  notas text,
  cambiado_por uuid,
  cambiado_at timestamp with time zone DEFAULT now(),
  CONSTRAINT siniestros_historial_pkey PRIMARY KEY (id),
  CONSTRAINT siniestros_historial_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id),
  CONSTRAINT siniestros_historial_cambiado_por_fkey FOREIGN KEY (cambiado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.usuarios (
  id uuid NOT NULL,
  nombre text NOT NULL,
  apellido text,
  telefono text,
  rol_id integer NOT NULL,
  oficina text,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.roles(id)
);
CREATE TABLE public.vendedores (
  id integer NOT NULL DEFAULT nextval('vendedores_id_seq'::regclass),
  nombre text NOT NULL,
  apellido text,
  telefono text,
  email text,
  oficina text,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  creado_por uuid,
  codigo text,
  CONSTRAINT vendedores_pkey PRIMARY KEY (id),
  CONSTRAINT vendedores_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id)
);